services:
  bot:
    build: .
    container_name: cinepolis-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Volume para manter o cache da sessão e evitar ter que logar novamente
      - ./session:/app/session
